# Generated by Django 5.2 on 2025-04-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
    ]
